// @ts-nocheck
import * as __fd_glob_61 from "../../generated/packages/gen/api/types.mdx?collection=docs"
import * as __fd_glob_60 from "../../generated/packages/gen/api/index.mdx?collection=docs"
import * as __fd_glob_59 from "../../generated/packages/gen/api/functions.mdx?collection=docs"
import * as __fd_glob_58 from "../../generated/packages/gen/api/examples.mdx?collection=docs"
import * as __fd_glob_57 from "../../generated/packages/enforcer/api/types.mdx?collection=docs"
import * as __fd_glob_56 from "../../generated/packages/enforcer/api/index.mdx?collection=docs"
import * as __fd_glob_55 from "../../generated/packages/enforcer/api/functions.mdx?collection=docs"
import * as __fd_glob_54 from "../../generated/packages/enforcer/api/examples.mdx?collection=docs"
import * as __fd_glob_53 from "../../generated/packages/core/api/types.mdx?collection=docs"
import * as __fd_glob_52 from "../../generated/packages/core/api/index.mdx?collection=docs"
import * as __fd_glob_51 from "../../generated/packages/core/api/functions.mdx?collection=docs"
import * as __fd_glob_50 from "../../generated/packages/core/api/examples.mdx?collection=docs"
import * as __fd_glob_49 from "../../generated/packages/doctest/api/types.mdx?collection=docs"
import * as __fd_glob_48 from "../../generated/packages/doctest/api/index.mdx?collection=docs"
import * as __fd_glob_47 from "../../generated/packages/doctest/api/functions.mdx?collection=docs"
import * as __fd_glob_46 from "../../generated/packages/doctest/api/examples.mdx?collection=docs"
import * as __fd_glob_45 from "../../generated/packages/cli/api/types.mdx?collection=docs"
import * as __fd_glob_44 from "../../generated/packages/cli/api/index.mdx?collection=docs"
import * as __fd_glob_43 from "../../generated/packages/cli/api/functions.mdx?collection=docs"
import * as __fd_glob_42 from "../../generated/packages/cli/api/examples.mdx?collection=docs"
import * as __fd_glob_41 from "../../generated/packages/api/api/types.mdx?collection=docs"
import * as __fd_glob_40 from "../../generated/packages/api/api/index.mdx?collection=docs"
import * as __fd_glob_39 from "../../generated/packages/api/api/functions.mdx?collection=docs"
import * as __fd_glob_38 from "../../generated/packages/api/api/examples.mdx?collection=docs"
import * as __fd_glob_37 from "../../generated/packages/gen/index.mdx?collection=docs"
import * as __fd_glob_36 from "../../generated/packages/enforcer/index.mdx?collection=docs"
import * as __fd_glob_35 from "../../generated/packages/doctest/index.mdx?collection=docs"
import * as __fd_glob_34 from "../../generated/packages/core/index.mdx?collection=docs"
import * as __fd_glob_33 from "../../generated/packages/cli/index.mdx?collection=docs"
import * as __fd_glob_32 from "../../generated/packages/api/types.mdx?collection=docs"
import * as __fd_glob_31 from "../../generated/packages/api/index.mdx?collection=docs"
import * as __fd_glob_30 from "../../generated/packages/api/functions.mdx?collection=docs"
import * as __fd_glob_29 from "../../generated/packages/api/examples.mdx?collection=docs"
import * as __fd_glob_28 from "../../generated/packages/index.mdx?collection=docs"
import * as __fd_glob_27 from "../../generated/guides/index.mdx?collection=docs"
import * as __fd_glob_26 from "../../generated/guides/getting-started.mdx?collection=docs"
import * as __fd_glob_25 from "../../generated/guides/error-handling.mdx?collection=docs"
import * as __fd_glob_24 from "../../generated/guides/configuration.mdx?collection=docs"
import * as __fd_glob_23 from "../../generated/index.mdx?collection=docs"
import * as __fd_glob_22 from "../../generated/getting-started.mdx?collection=docs"
import * as __fd_glob_21 from "../../generated/faq.mdx?collection=docs"
import * as __fd_glob_20 from "../../generated/contributing.mdx?collection=docs"
import * as __fd_glob_19 from "../../generated/configuration.mdx?collection=docs"
import * as __fd_glob_18 from "../../generated/concepts.mdx?collection=docs"
import * as __fd_glob_17 from "../../generated/changelog.mdx?collection=docs"
import { default as __fd_glob_16 } from "../../generated/packages/doctest/api/meta.json?collection=docs"
import { default as __fd_glob_15 } from "../../generated/packages/gen/api/meta.json?collection=docs"
import { default as __fd_glob_14 } from "../../generated/packages/enforcer/api/meta.json?collection=docs"
import { default as __fd_glob_13 } from "../../generated/packages/cli/api/meta.json?collection=docs"
import { default as __fd_glob_12 } from "../../generated/packages/core/api/meta.json?collection=docs"
import { default as __fd_glob_11 } from "../../generated/packages/api/api/meta.json?collection=docs"
import { default as __fd_glob_10 } from "../../generated/packages/gen/meta.json?collection=docs"
import { default as __fd_glob_9 } from "../../generated/packages/doctest/meta.json?collection=docs"
import { default as __fd_glob_8 } from "../../generated/packages/enforcer/meta.json?collection=docs"
import { default as __fd_glob_7 } from "../../generated/packages/core/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../../generated/packages/cli/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../../generated/packages/api/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../../generated/guides/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../../generated/packages/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../../generated/api/openapi.json?collection=docs"
import { default as __fd_glob_1 } from "../../generated/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../../generated/ckm.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "../generated", {"ckm.json": __fd_glob_0, "meta.json": __fd_glob_1, "api/openapi.json": __fd_glob_2, "packages/meta.json": __fd_glob_3, "guides/meta.json": __fd_glob_4, "packages/api/meta.json": __fd_glob_5, "packages/cli/meta.json": __fd_glob_6, "packages/core/meta.json": __fd_glob_7, "packages/enforcer/meta.json": __fd_glob_8, "packages/doctest/meta.json": __fd_glob_9, "packages/gen/meta.json": __fd_glob_10, "packages/api/api/meta.json": __fd_glob_11, "packages/core/api/meta.json": __fd_glob_12, "packages/cli/api/meta.json": __fd_glob_13, "packages/enforcer/api/meta.json": __fd_glob_14, "packages/gen/api/meta.json": __fd_glob_15, "packages/doctest/api/meta.json": __fd_glob_16, }, {"changelog.mdx": __fd_glob_17, "concepts.mdx": __fd_glob_18, "configuration.mdx": __fd_glob_19, "contributing.mdx": __fd_glob_20, "faq.mdx": __fd_glob_21, "getting-started.mdx": __fd_glob_22, "index.mdx": __fd_glob_23, "guides/configuration.mdx": __fd_glob_24, "guides/error-handling.mdx": __fd_glob_25, "guides/getting-started.mdx": __fd_glob_26, "guides/index.mdx": __fd_glob_27, "packages/index.mdx": __fd_glob_28, "packages/api/examples.mdx": __fd_glob_29, "packages/api/functions.mdx": __fd_glob_30, "packages/api/index.mdx": __fd_glob_31, "packages/api/types.mdx": __fd_glob_32, "packages/cli/index.mdx": __fd_glob_33, "packages/core/index.mdx": __fd_glob_34, "packages/doctest/index.mdx": __fd_glob_35, "packages/enforcer/index.mdx": __fd_glob_36, "packages/gen/index.mdx": __fd_glob_37, "packages/api/api/examples.mdx": __fd_glob_38, "packages/api/api/functions.mdx": __fd_glob_39, "packages/api/api/index.mdx": __fd_glob_40, "packages/api/api/types.mdx": __fd_glob_41, "packages/cli/api/examples.mdx": __fd_glob_42, "packages/cli/api/functions.mdx": __fd_glob_43, "packages/cli/api/index.mdx": __fd_glob_44, "packages/cli/api/types.mdx": __fd_glob_45, "packages/doctest/api/examples.mdx": __fd_glob_46, "packages/doctest/api/functions.mdx": __fd_glob_47, "packages/doctest/api/index.mdx": __fd_glob_48, "packages/doctest/api/types.mdx": __fd_glob_49, "packages/core/api/examples.mdx": __fd_glob_50, "packages/core/api/functions.mdx": __fd_glob_51, "packages/core/api/index.mdx": __fd_glob_52, "packages/core/api/types.mdx": __fd_glob_53, "packages/enforcer/api/examples.mdx": __fd_glob_54, "packages/enforcer/api/functions.mdx": __fd_glob_55, "packages/enforcer/api/index.mdx": __fd_glob_56, "packages/enforcer/api/types.mdx": __fd_glob_57, "packages/gen/api/examples.mdx": __fd_glob_58, "packages/gen/api/functions.mdx": __fd_glob_59, "packages/gen/api/index.mdx": __fd_glob_60, "packages/gen/api/types.mdx": __fd_glob_61, });